local colors = require("themer").get_theme_table("theme")
local darken = require("themer.colors").blend

return {
	BufferlineRun = { fg = colors.color4, bg = darken(colors.color4, colors.black, 0.15) },
	BufferlineSplit = { fg = colors.color2, bg = darken(colors.color2, colors.black, 0.15) },
	BufferlineTheme = { fg = colors.color5, bg = darken(colors.color5, colors.black, 0.15) },
	BUfferlineTrasparency = { fg = colors.color6, bg = darken(colors.color6, colors.black, 0.15) },
	BufferlineCloseAll = { fg = colors.color9, bg = darken(colors.color9, colors.black, 0.15) },

	BufferLineBackground = { fg = colors.color7, bg = colors.color0 },
	BufferLineBuffer = { fg = colors.color7, bg = colors.color0 },
	BufferLineBufferSelected = { fg = colors.background, bg = colors.color4, bold = true },
	BufferLineBufferVisible = { fg = colors.color4, bg = colors.color0 },
	BufferLineCloseButton = { fg = colors.color1, bg = colors.color0 },
	BufferLineCloseButtonSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineCloseButtonVisible = { fg = colors.color1, bg = colors.color0 },
	BufferLineDuplicate = { fg = colors.color8, bg = colors.color0 },
	BufferLineDuplicateSelected = { fg = colors.color8, bg = colors.color0 },
	BufferLineDuplicateVisible = { fg = colors.color8, bg = colors.color0 },
	BufferLineFill = { fg = colors.color7, bg = colors.background },
	BufferLineIndicatorSelected = { fg = colors.color4, bg = colors.color4 },
	BufferLineIndicatorVisible = { fg = colors.color0, bg = colors.color0 },
	BufferLineModified = { fg = colors.color2, bg = colors.color0 },
	BufferLineModifiedSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineModifiedVisible = { fg = colors.color2, bg = colors.color0 },
	BufferLineOffsetSeparator = { fg = colors.color4, bg = colors.color4 },
	BufferLinePick = { fg = colors.color13, bg = colors.color0, bold = true },
	BufferLinePickSelected = { fg = colors.color11, bg = colors.color4, bold = true },
	BufferLinePickVisible = { fg = colors.color11, bg = colors.color0, bold = true },
	BufferLineSeparator = { fg = colors.color0, bg = colors.color0 },
	BufferLineSeparatorSelected = { fg = colors.color4, bg = colors.color4 },
	BufferLineSeparatorVisible = { fg = colors.color0, bg = colors.color0 },
	BufferLineTabClose = { fg = colors.color1, bg = colors.background },
	BufferLineTab = { fg = colors.color7, bg = colors.color0 },
	BufferLineTabSelected = { fg = colors.color4, bg = colors.background, bold = true },
	BufferLineTabSeparator = { fg = colors.color0, bg = colors.color0 },
	BufferLineTabSeparatorSelected = { fg = colors.background, bg = colors.background },

	-- Language icons

	BufferLineDevIconC = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconCSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconCsharp = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconCsharpSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconLua = { fg = colors.color12, bg = colors.color0 },
	BufferLineDevIconLuaSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconPy = { fg = colors.color10, bg = colors.color0 },
	BufferLineDevIconPySelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconcss = { fg = colors.color6, bg = colors.color0 },
	BufferLineDevIconcssSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIcondeb = { fg = colors.color1, bg = colors.color0 },
	BufferLineDevIcondebSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconDockerfile = { fg = colors.color14, bg = colors.color0 },
	BufferLineDevIconDockerfileSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconhtml = { fg = colors.color11, bg = colors.color0 },
	BufferLineDevIconhtmlSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconjpeg = { fg = colors.color13, bg = colors.color0 },
	BufferLineDevIconjpegSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconjs = { fg = colors.color3, bg = colors.color0 },
	BufferLineDevIconjsSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconJava = { fg = colors.color9, bg = colors.color0 },
	BufferLineDevIconJavaSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconDart = { fg = colors.color12, bg = colors.color0 },
	BufferLineDevIconDartSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconVue = { fg = colors.color2, bg = colors.color0 },
	BufferLineDevIconVueSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconTSX = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconTSXSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconJSX = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconJSXSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconSvelte = { fg = colors.color1, bg = colors.color0 },
	BufferLineDevIconSvelteSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconVim = { fg = colors.color10, bg = colors.color0 },
	BufferLineDevIconVimSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconREADME = { fg = colors.color5, bg = colors.color0 },
	BufferLineDevIconREADMESelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconLICENSE = { fg = colors.color2, bg = colors.color0 },
	BufferLineDevIconLICENSESelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconpackage = { fg = colors.color3, bg = colors.color0 },
	BufferLineDevIconpackageSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconjson = { fg = colors.color7, bg = colors.color0 },
	BufferLineDevIconjsonSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconxml = { fg = colors.color13, bg = colors.color0 },
	BufferLineDevIconxmlSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconPhp = { fg = colors.color13, bg = colors.color0 },
	BufferLineDevIconPhpSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconCpp = { fg = colors.color12, bg = colors.color0 },
	BufferLineDevIconCppSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconDefault = { fg = colors.color1, bg = colors.color0 },
	BufferLineDevIconDefaultSelected = { fg = colors.background, bg = colors.color4 },

	-- Configuration files

	BufferLineDevIconconf = { fg = colors.color6, bg = colors.color0 },
	BufferLineDevIconconfSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconyaml = { fg = colors.color7, bg = colors.color0 },
	BufferLineDevIconyamlSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIcontoml = { fg = colors.color3, bg = colors.color0 },
	BufferLineDevIcontomlSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconini = { fg = colors.color5, bg = colors.color0 },
	BufferLineDevIconiniSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconenv = { fg = colors.color2, bg = colors.color0 },
	BufferLineDevIconenvSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconlock = { fg = colors.color8, bg = colors.color0 },
	BufferLineDevIconlockSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconlog = { fg = colors.color9, bg = colors.color0 },
	BufferLineDevIconlogSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconcsv = { fg = colors.color11, bg = colors.color0 },
	BufferLineDevIconcsvSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIcondb = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIcondbSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconMakefile = { fg = colors.color9, bg = colors.color0 },
	BufferLineDevIconMakefileSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIcongitignore = { fg = colors.color8, bg = colors.color0 },
	BufferLineDevIcongitignoreSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconBashrc = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconBashrcSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconZshrc = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconZshrcSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconNushell = { fg = colors.color13, bg = colors.color0 },
	BufferLineDevIconNushellSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconOpenbox = { fg = colors.color5, bg = colors.color0 },
	BufferLineDevIconOpenboxSelected = { fg = colors.background, bg = colors.color4 },
	BufferLineDevIconXresources = { fg = colors.color4, bg = colors.color0 },
	BufferLineDevIconXresourcesSelected = { fg = colors.background, bg = colors.color4 },
}
