local colors = require("themer").get_theme_table("theme")

return {
	DevIconc = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconcss = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIcondeb = { fg = colors.color12 }, -- cyan (#5fb0fc)
	DevIconDockerfile = { fg = colors.color12 }, -- cyan (#5fb0fc)
	DevIconhtml = { fg = colors.color5 }, -- rosa (#c397d8)
	DevIconjpeg = { fg = colors.color13 }, -- morado (#b77ee0)
	DevIconjpg = { fg = colors.color13 }, -- morado (#b77ee0)
	DevIconjs = { fg = colors.color11 }, -- amarillo (#fccf67)
	DevIconkt = { fg = colors.color9 }, -- naranja (#fb7373)
	DevIconlock = { fg = colors.color1 }, -- rojo (#f87070)
	DevIconlua = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconmp3 = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconmp4 = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconout = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconpng = { fg = colors.color13 }, -- morado (#b77ee0)
	DevIconpy = { fg = colors.color12 }, -- cyan (#5fb0fc)
	DevIcontoml = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconts = { fg = colors.color14 }, -- turquesa (#54c3d6)
	DevIconttf = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconrb = { fg = colors.color5 }, -- rosa (#c397d8)
	DevIconrpm = { fg = colors.color9 }, -- naranja (#fb7373)
	DevIconvue = { fg = colors.color10 }, -- verde (#36c692)
	DevIconwoff = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconwoff2 = { fg = colors.color7 }, -- blanco (#d4d4d5)
	DevIconxz = { fg = colors.color11 }, -- amarillo (#fccf67)
	DevIconzip = { fg = colors.color11 }, -- amarillo (#fccf67)
	DevIconZig = { fg = colors.color9 }, -- naranja (#fb7373)
	DevIconMd = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconTSX = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconJSX = { fg = colors.color4 }, -- azul (#7ab0df)
	DevIconSvelte = { fg = colors.color1 }, -- rojo (#f87070)
	DevIconJava = { fg = colors.color9 }, -- naranja (#fb7373)
	DevIconDart = { fg = colors.color12 }, -- cyan (#5fb0fc)
	DevIconCsharp = { fg = colors.color6 }, -- púrpura (#a277ff)
	DevIconCsproj = { fg = colors.color6 }, -- púrpura (#a277ff)
}
