local colors = require("themer").get_theme_table("theme")

return {
	Boolean = { fg = colors.color11 },
	Character = { fg = colors.color1 },
	Conditional = { fg = colors.color5 },
	Constant = { fg = colors.color1 },
	Define = { fg = colors.color5, sp = "none" },
	Delimiter = { fg = colors.color13 },
	Float = { fg = colors.color11 },
	Variable = { fg = colors.foreground },
	Function = { fg = colors.color4 },
	Identifier = { fg = colors.color1, sp = "none" },
	Include = { fg = colors.color4 },
	Keyword = { fg = colors.color5 },
	Label = { fg = colors.color3 },
	Number = { fg = colors.color11 },
	Operator = { fg = colors.foreground, sp = "none" },
	PreProc = { fg = colors.color3 },
	Repeat = { fg = colors.color3 },
	Special = { fg = colors.color6 },
	SpecialChar = { fg = colors.color13 },
	Statement = { fg = colors.color1 },
	StorageClass = { fg = colors.color3 },
	String = { fg = colors.color2 },
	Structure = { fg = colors.color5 },
	Tag = { fg = colors.color3 },
	Todo = { fg = colors.color3, bg = colors.color0 },
	Type = { fg = colors.color3, sp = "none" },
	Typedef = { fg = colors.color3 },
}
