local colors = require("themer").get_theme_table("theme")

return {
	["@variable"] = { fg = colors.foreground },
	["@variable.builtin"] = { fg = colors.color11, bold = true },
	["@variable.parameter"] = { fg = colors.color1, bold = true },
	["@variable.member"] = { fg = colors.color1 },
	["@variable.member.key"] = { fg = colors.color1 },

	["@module"] = { fg = colors.color1 },
	-- ["@module.builtin"] = { fg = colors.color1 },

	["@constant"] = { fg = colors.color11, bold = true },
	["@constant.builtin"] = { fg = colors.color11, bold = true },
	["@constant.macro"] = { fg = colors.color1, bold = true },

	["@string"] = { fg = colors.color2 },
	["@string.regex"] = { fg = colors.color6 },
	["@string.escape"] = { fg = colors.color6 },
	["@character"] = { fg = colors.color1 },
	-- ["@character.special"] = { fg = colors.color1 },
	["@number"] = { fg = colors.color11 },
	["@number.float"] = { fg = colors.color11 },
	["@boolean"] = { colors.colo5, bold = true },
	["@parameter"] = { colors.colo3, bold = true },

	["@annotation"] = { fg = colors.color13 },
	["@attribute"] = { fg = colors.color3 },
	["@error"] = { fg = colors.color1 },

	["@keyword.exception"] = { fg = colors.color1 },
	["@keyword"] = { fg = colors.color5, bold = true, italic = true },
	["@keyword.function"] = { fg = colors.color5, bold = true, italic = true },
	["@keyword.return"] = { fg = colors.color5, bold = true, italic = true },
	["@keyword.operator"] = { fg = colors.color5, bold = true },
	["@keyword.import"] = { link = "Include" },
	["@keyword.conditional"] = { fg = colors.color5 },
	["@keyword.conditional.ternary"] = { fg = colors.color5 },
	["@keyword.repeat"] = { fg = colors.color3 },
	["@keyword.storage"] = { fg = colors.color3 },
	["@keyword.directive.define"] = { fg = colors.color5, bold = true },
	["@keyword.directive"] = { fg = colors.color3 },

	["@function"] = { fg = colors.color4, bold = true },
	["@function.builtin"] = { fg = colors.color4 },
	["@function.macro"] = { fg = colors.color1, bold = true },
	["@function.call"] = { fg = colors.color4, bold = true },
	["@function.method"] = { fg = colors.color4, bold = true },
	["@function.method.call"] = { fg = colors.color4, bold = true },
	["@constructor"] = { fg = colors.color6, bold = true },

	["@operator"] = { fg = colors.foreground },
	["@reference"] = { fg = colors.foreground },
	["@punctuation.bracket"] = { fg = colors.color13 },
	["@punctuation.delimiter"] = { fg = colors.color13 },
	["@symbol"] = { fg = colors.color2 },
	["@tag"] = { fg = colors.color3 },
	["@tag.attribute"] = { fg = colors.color1, italic = true },
	["@tag.delimiter"] = { fg = colors.color13 },
	["@text"] = { fg = colors.foreground },
	["@text.emphasis"] = { fg = colors.color11, italic = true },
	["@text.strike"] = { fg = colors.color13, strikethrough = true },
	["@type.builtin"] = { fg = colors.color3 },
	["@definition"] = { sp = colors.color0, underline = true },
	["@scope"] = { bold = true },
	["@property"] = { fg = colors.color1 },

	-- markup
	["@markup.heading"] = { fg = colors.color4 },
	["@markup.raw"] = { fg = colors.color11 },
	["@markup.link"] = { fg = colors.color1 },
	["@markup.link.url"] = { fg = colors.color11, underline = true },
	["@markup.link.label"] = { fg = colors.color6 },
	["@markup.list"] = { fg = colors.color1 },
	["@markup.strong"] = { bold = true },
	["@markup.underline"] = { underline = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.quote"] = { bg = colors.darker },

	["@comment"] = { fg = colors.comment },
	["@comment.todo"] = { fg = colors.color8, bg = colors.color15 },
	["@comment.warning"] = { fg = colors.darker, bg = colors.color11 },
	["@comment.note"] = { fg = colors.black, bg = colors.color12 },
	["@comment.danger"] = { fg = colors.darker, bg = colors.color1 },

	["@diff.plus"] = { fg = colors.color2 },
	["@diff.minus"] = { fg = colors.color1 },
	["@diff.delta"] = { fg = colors.color7 },
}
